### ISSUE TITLE
Moodle Plugin

### ISSUE THREAD

**Issue by pauloafpjunior** [marciovsena/bibleapi#102]
Hi Márcio.

bibleapi is amazing. Thank you so much. I'm considering to develop a Moodle (it is a well-known learning management system) Plugin that uses this API to present daily verses to the users.

I'd like to request your permisson and opinion.

Best regards. Paulo.

**Comment by marciovsena** [comment]
Paulo, thank you very much for using the bibleapi. Of course, share the repository to add to the README of this repository.

Best regards.
