### ISSUE TITLE
Link to documentation not working

### ISSUE THREAD

**Issue by herculesgabriel** [marciovsena/bibleapi#126]
I came from the website and tried to access the documentation, but it's not working

https://github.com/marciovsena/bibleapi/blob/dev/DOCUMENTATION.md

**Comment by marciovsena** [comment]
@herculesgabriel the correct link is https://github.com/marciovsena/bibleapi/blob/master/DOCUMENTATION.md.

**Comment by herculesgabriel** [comment]
So fix the link on the webpage ;)
