### ISSUE TITLE
How to query "Jó" book ?

### ISSUE THREAD

**Issue by humbertocruz** [marciovsena/bibleapi#25]
how to query the book of "Jó" ?

verses/acf/jo/1 brings "João" book and verses/acf/jó/1 is not found.
thanks

**Comment by marciovsena** [comment]
@humbertocruz we have a bug. I will adjust this and update in production.

**Comment by marciovsena** [comment]
@humbertocruz try `verses/acf/job/1`.

I will update the documentation with this information, thank you

**Comment by humbertocruz** [comment]
Thanks
