### ISSUE TITLE
Access-Control-Allow-Origin - Problemas ao tentar acessar a API via ReactJS

### ISSUE THREAD

**Issue by winstonsec** [marciovsena/bibleapi#28]
Olá, boa noite. 

Estou tentando acessar a API via reactjs mas sempre aparece essa mensagem de erro: 

Access to XMLHttpRequest at 'https://bibleapi.co/api/books/gn' from origin 'https://retomada.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value 'false'.

**Comment by marciovsena** [comment]
@winstonsec antes de tudo, desculpe a demora. Como estava refatorando todo o projeto, não consegui manter a versão anterior, se puder testar novamente. Creio que já corrigimos este problema.
