### ISSUE TITLE
Responsive menu doesn't close

### ISSUE THREAD

**Issue by vanribeiro** [marciovsena/bibleapi#29]
Hi, Marcos! Congrats about this project!
Well, surfing on the docs link, I noted a problem with the responsive menu. It doesn't close on the mobile phone. I still haven't  test it on desktop browser.

![Screenshot_20191231-040116](https://user-images.githubusercontent.com/9155761/71612176-55496080-2b7d-11ea-99c3-16ddcdf156bb.png)

**Comment by marciovsena** [comment]
I'm closing this issue, as the new documentation will be on the github itself and has been updated in PR #34
