### ISSUE TITLE
Plugin WordPress

### ISSUE THREAD

**Issue by thallesbrandao** [marciovsena/bibleapi#45]
**Olá,** 
Gostaria de contribuir com o projeto criando um plugin para o WordPress. 
Caso seja autorizado podemos discutir nesse issue os parâmetros.

Aguardamos autorização do desenvolvedor...

**Comment by marciovsena** [comment]
@thallesbrandao está sempre autorizado 😄 

Qual ou Quais seriam as funcionalidades deste plugin?

- Versículo do dia
- O usuário de um site consumir um passagem bíblica
- O próprio site indicar um versículo com base na configuração do painel de administração

**Comment by thallesbrandao** [comment]
@marciovsena Obrigado pela autorização ;)

Sobre as funcionalidades pensei em algo diferente como:

https://www.gospelminas.com/biblia-online/ (Exemplo no Projeto o de usei a API, algo bem basico)
https://biblia.gospelprime.com.br/acf/

Podemos também colocar as funções sugeridas como complementos do plugin.

Vamos criar o projeto inicial. 

Qual nome podemos colocar no plugin?

**Comment by marciovsena** [comment]
@thallesbrandao eu iria com o nome `biblidigital-wp`. Te dando spoiler, esse é o novo nome da bibleapi, inclusive já temos o domínio, estamos finalizando a nova landing page e já engatilhando as próximas ferramentas open source com o mesmo branding
