### ISSUE TITLE
Criação de um novo usuário

### ISSUE THREAD

**Issue by jefter-dev** [marciovsena/bibleapi#81]
Olá, estou tentando criar um usuário! mas recebo de retorno a seguinte mensagem.
<pre>{"msg":"{name}(String), {email}(String), {notifications}(Boolean) and {password}(String) are required"}</pre>

Estou utilizando php para fazer a requisição.
![git 1](https://user-images.githubusercontent.com/63052317/78795016-da1cf500-798a-11ea-9077-adc1175834b6.JPG)
![git 2](https://user-images.githubusercontent.com/63052317/78795022-db4e2200-798a-11ea-8459-439071997517.JPG)

Pode verificar? 
Abraços!

**Comment by marciovsena** [comment]
@jefter-dev aparentemente o `notifications` é uma `string`, mas precisa ser um `boolean`. Eu recomendo que você nem faça código da criação de usuário, a não ser que a sua aplicação tenha múltiplos usuários e cada um faça essa requisição com usuários diferentes. 

Acredito que o melhor é você criar uma única vez este usuário, pode ser pelo postman, e passe o token do seu usuário em todas as requisições. Entende?

**Comment by jefter-dev** [comment]
Boa tarde, eu fiz o q você me disse, mas mesmo assim obtenho a mesma
resposta.
E tentei pelo Postman, também recebo a mesma resposta por lá. E a minha
intensão, não é criar vários usuários, e sim somente criar 1 único usuário,
para q a minha aplicação rode sem limite de acessos.

E só para confirmar, tens previsão de quando vai lançar as outras
traduções?

E obg de toda forma, abraço!

Em Qui, 9 de abr de 2020 17:41, Márcio Vinícius Sena <
notifications@github.com> escreveu:

**Comment by marciovsena** [comment]
@jefter-dev segue um exemplo da requisição que te falei via CURL

**Request:**
```
curl --location --request POST 'http://bibleapi.co/api/users/' \
--header 'Content-Type: application/json' \
--header 'Content-Type: text/plain' \
--data-raw '{
	"name": "Márcio Vinícius Oliveira Sena",
	"email": "contato@marciosena.com.br",
	"password": "senha",
	"notifications": true
}
```

**Response**

```
{
    "name": "Márcio Vinícius Oliveira Sena",
    "email": "contatos@marciosena.com.br",
    "notifications": true,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6I.."
}
```
