### ISSUE TITLE
use token on GET

### ISSUE THREAD

**Issue by gustavosilva-gss** [marciovsena/bibleapi#85]
Quando eu faço alguma operação de GET, onde coloco o token (para não ter limitações)?
Seria no header?
Estou usando c#, mas só me dando uma explicação em outra linguagem já está bom

caso te interesse: usando o discord encontrei alguns bots que mostravam verículos, mas os que aceitavam versões em portugues não aceitavam o nome do livro em portugues, então criei um bot simples para isso
ainda faltam alguns ajustes, mas estou feliz com o resultado
obrigado

**Comment by marciovsena** [comment]
@gustavosilva-gss sim, no header como Bearer Token

Exemplo de código Nodejs
```
var request = require('request');
var options = {
  'method': 'GET',
  'url': 'http://bibleapi.co/api/verses/rvr/gn/1/1',
  'headers': {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlN1biBGZWIgMDIgMjAyMCAwMjo1NTozMyBHTVQrMDAwMC5jb250YXRvQG1hcmNpb3NlbmEuY29tLmJyIiwiaWF0IjoxNTgwNjEyMTMzfQ.1quctM_3Rwv0w7NuyqPVX3fRZ2FOAtqz1Tcy4xCVCX4'
  }
};
request(options, function (error, response) { 
  if (error) throw new Error(error);
  console.log(response.body);
});
```
